import os
import requests
import pandas as pd
from sqlalchemy.orm import Session
from models.gitlab_prediction import GitLabPrediction
from models.ml.ml_model import MLModel
from services.ml.ml_service import extract_features, predict_model

GITLAB_TOKEN = os.getenv("GITLAB_TOKEN")

def process_mr_event(db: Session, payload: dict):
    """
    Handle GitLab Merge Request Hook payload.
    Extracts metadata, performs ML risk prediction, persists in DB, and posts to GitLab.
    """
    object_attributes = payload.get("object_attributes", {})
    mr_id = object_attributes.get("iid")
    project_id = object_attributes.get("target_project_id")
    branch = object_attributes.get("source_branch")
    last_commit = object_attributes.get("last_commit", {})
    commit_sha = last_commit.get("id")
    
    # 1. Prepare raw metadata for feature extraction
    # GitLab MR hooks provide some stats in object_attributes
    raw_data = {
        "additions": object_attributes.get("total_time_spent", 0) % 50, # Dummy heuristic if real stats missing
        "deletions": object_attributes.get("time_estimate", 0) % 50,
        "num_files": 1, 
        "message": last_commit.get("message", "Merge Request Update"),
        "timestamp": last_commit.get("timestamp")
    }
    
    # Try to find real stats in the payload (GitLab often includes them in object_attributes)
    if "total_additions" in object_attributes:
        raw_data["additions"] = object_attributes["total_additions"]
    if "total_deletions" in object_attributes:
        raw_data["deletions"] = object_attributes["total_deletions"]
    
    # Heuristic based on MR description length or other fields if available
    # In a real integration, we'd call /projects/:id/merge_requests/:iid/changes
    
    # 2. Extract Features
    df = pd.DataFrame([raw_data])
    features_df = extract_features(df)
    features = features_df.iloc[0].to_dict()
    
    # 3. Get Active Model & Predict
    active_model = db.query(MLModel).filter(MLModel.is_active == True).first()
    if not active_model:
        return {"status": "error", "message": "No active ML model found"}
        
    prediction = predict_model(active_model, features)
    
    import json
    
    # 4. Persist to DB
    git_pred = GitLabPrediction(
        mr_id=mr_id,
        project_id=project_id,
        branch=branch,
        commit_sha=commit_sha,
        risk_score=prediction["risk"],
        risk_category=prediction["risk_category"],
        explanation=prediction["reason"],
        shap_json=json.dumps(prediction.get("shap_values", [])),
        suggestions_json=json.dumps(prediction.get("suggestions", [])),
        features_json=json.dumps(features)
    )
    db.add(git_pred)
    db.commit()
    db.refresh(git_pred)
    
    # 5. Post to GitLab MR (if token is set)
    if GITLAB_TOKEN:
        post_mr_comment(project_id, mr_id, prediction)
        git_pred.posted_to_gitlab = True
        db.commit()
        
    return {
        "status": "success",
        "mr_id": mr_id,
        "risk": prediction["risk"],
        "category": prediction["risk_category"]
    }

def post_mr_comment(project_id: int, mr_id: int, prediction: dict):
    """
    Post a formatted risk report back to the GitLab Merge Request.
    """
    url = f"https://gitlab.com/api/v4/projects/{project_id}/merge_requests/{mr_id}/notes"
    headers = {"PRIVATE-TOKEN": GITLAB_TOKEN}
    
    risk_percent = round(prediction["risk"] * 100, 1)
    status_icon = "🔴" if prediction["risk"] > 0.65 else ("🟡" if prediction["risk"] > 0.35 else "🟢")
    
    comment_body = f"""
### {status_icon} PipelineAI Risk Report
**Build Failure Probability:** `{risk_percent}%` ({prediction['risk_category']} Risk)

**Top Signals:**
{prediction['reason']}

**Actionable Insights:**
- Review the logic in late-night sessions to avoid fatigue errors.
- Ensure test coverage covers the modified lines (shrunk diff suggested).

*Generated by PipelineAI - Model Version: {prediction['model_version']}*
    """
    
    try:
        requests.post(url, headers=headers, json={"body": comment_body})
    except Exception as e:
        print(f"Failed to post to GitLab: {e}")
