version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cicd_user
      POSTGRES_PASSWORD: cicd_pass
      POSTGRES_DB: cicd_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ../backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://cicd_user:cicd_pass@db:5432/cicd_db
    depends_on:
      - db

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
